baseURL: "http://osmialowski.net"
languageCode: "en-us"
metaDataFormat: "yaml"
permalinks:
  articles: "/:title/"

title: "Andrzej Ośmiałowski - Software Developer"
copyright: "Licensed under a Creative Commons Attribution."

googleAnalytics: "UA-78447846-2"
discusShortname: "aosmialowski"

menu:
  main:
    - name: "Home"
      weight: 100
      identifier: "home"
      url: "/"
    - name: "Resume"
      weight: 400
      identifier: "resume"
      url: "/files/resume.pdf"
    - name: "RSS"
      weight: 500
      identifier: "rss"
      url: "index.xml"

params:
  meta:
    description: "Development blog by Andrzej Ośmiałowski"
    keywords: "development, php, java, spring, doctrine, symfony"
    intro: "Hello! I'm Andrzej, a software developer & freelance consultant from Wrocław, PL."
  social:
    facebook: "aosmialowski"
    github: "aosmialowski"
    linkedin: "osmialowski"
    twitter: "aosmialowski"

author:
  name: "Andrzej Ośmiałowski"
  email: "me@osmialowski.net"